### ISSUE TITLE
Format of Suggestion.create

### ISSUE THREAD

**Issue by robs16** [cds-hooks/docs#23]
The documentation for Suggestion.create states:
> string. new resource(s) that this suggestion applies within the current activity (e.g. for medication-prescribe, this holds the updated prescription as proposed by the suggestion).

The .yml in Swagger shows:
```
  Suggestion:
    type: object
    properties:
      label:
        type: string
      create:
        type: array
        items:
          type: object
      delete:
        type: array
        items:
          type: object
```

A string is not sufficient to hold the resource, so the docs need updating for consistency. Should this be an array of resources, a Bundle.entry (like prefetch), or a Bundle? Should Suggestion.delete be a simple list of strings or consistent with create?
